<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Feedback;

class FeedbackSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        Feedback::truncate();
        
        $feedbacks = [
            ['name' => 'Wahid Ullah',
            'comment' => 'It was nice experience. Learn many things.',
            'ratting' => 3,
            'date' => now(),
            'user_id' => 3,
            'course_id' => 10,
            ],
            ['name' => 'Naseem Ullah',
            'comment' => 'It was nice experience. Learn many things.',
            'ratting' => 2,
            'date' => now(),
            'user_id' => 4,
            'course_id' => 10,
            ],
            ['name' => 'Qasid Mehmood',
            'comment' => 'It was nice experience. Learn many things',
            'ratting' => 5,
            'date' => now(),
            'user_id' => 3,
            'course_id' => 10,
            ],
            ['name' => 'Yasir shah',
            'comment' => 'It was nice experience. Learn many things',
            'ratting' => 5,//number from 1 - 5
            'date' => now(),
            'user_id' => 3,
            'course_id' => 10,
            ],
            ['name' => 'Saeed Ullah',
            'comment' => 'It was nice experience. Learn many new things',
            'ratting' => 4,
            'date' => now(),
            'user_id' => 3,
            'course_id' => 10,
            ],
            ['name' => 'Naeeda anjum',
            'comment' => 'It was nice experience. Learn many new things',
            'ratting' => 4,
            'date' => now(),
            'user_id' => 3,
            'course_id' => 10,
            ],
            ['name' => 'Abrar Ahmed',
            'comment' => 'It was nice experience. Learn many new things',
            'ratting' => 5,
            'date' => now(),
            'user_id' => 3,
            'course_id' => 10,
            ],
            ['name' => 'Sajid Khan',
            'comment' => 'It was nice experience. Learn many new things',
            'ratting' => 4,
            'date' => now(),
            'user_id' => 3,
            'course_id' => 10,
            ],
            ['name' => 'Hamid Nadeem',
            'comment' => 'It was nice experience. Learn many new things',
            'ratting' => 5,
            'date' => now(),
            'user_id' => 3,
            'course_id' => 10,
            ],
            ['name' => 'Sanaullah',
            'comment' => 'It was nice experience. Learn many new things',
            'ratting' => 5,
            'date' => now(),
            'user_id' => 3,
            'course_id' => 10,
            ],
            ['name' => 'Abdullah',
            'comment' => 'It was nice experience. Learn many new things',
            'ratting' => 5,
            'date' => now(),
            'user_id' => 3,
            'course_id' => 10,
            ],
            ['name' => 'Naila Khan',
            'comment' => 'It was nice experience. Learn many new things',
            'ratting' => 5,
            'date' => now(),
            'user_id' => 3,
            'course_id' => 10,
            ],
            ['name' => 'Abdul Malik',
            'comment' => 'It was nice experience. Learn many new things',
            'ratting' => 5,
            'date' => now(),
            'user_id' => 3,
            'course_id' => 10,
            ],
            ['name' => 'Sania',
            'comment' => 'It was nice experience. Learn many new things',
            'ratting' => 4,
            'date' => now(),
            'user_id' => 3,
            'course_id' => 10,
            ],
            ['name' => 'Gul Badin',
            'comment' => 'It was nice experience. Learn many new things',
            'ratting' => 5,
            'date' => now(),
            'user_id' => 3,
            'course_id' => 10,
            ],
            ['name' => 'Ikhlaq saeed',
            'comment' => 'It was nice experience. Learn many new things',
            'ratting' => 4,
            'date' => now(),
            'user_id' => 3,
            'course_id' => 10,
            ],
            ['name' => 'Shah Muhammad',
            'comment' => 'It was nice experience. Learn many new things',
            'ratting' => 5,
            'date' => now(),
            'user_id' => 3,
            'course_id' => 10,
            ],
            ['name' => 'Izat Khan',
            'comment' => 'It was nice experience. Learn many new things',
            'ratting' => 4,
            'date' => now(),
            'user_id' => 3,
            'course_id' => 10,
            ],
            ['name' => 'Abdul Hadi',
            'comment' => 'It was nice experience. Learn many new things',
            'ratting' => 5,
            'date' => now(),
            'user_id' => 3,
            'course_id' => 10,
            ],
            ['name' => 'Saad Hanan',
            'comment' => 'It was nice experience. Learn many new things',
            'ratting' => 5,
            'date' => now(),
            'user_id' => 3,
            'course_id' => 10,
            ],
        ];
        
        Feedback::insert($feedbacks);
    }
}
